### ISSUE TITLE
Consider using poetry instead of pip

### ISSUE THREAD

**Issue by cortadocodes** [octue/octue-sdk-python#392]
Currently, repetitive dependency resolution occurs on every single install and CI run, wasting time and energy. Using `poetry` would potentially mean this is only done once instead of `n` times.

**Comment by thclark** [comment]
Note that you should also add a CI check that the lockfile is up to date if using poetry. Here is a GHA that should do it:
```yml
name: check-lockfile

on:
  # or whatever
  push:
  workflow_dispatch:

jobs:
  check_poetry_lockfile:
    name: Check Poetry Lockfile
    if: "!contains(github.event.head_commit.message, 'skipci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Check Python Package Lockfile
        run: poetry check
```
