### ISSUE TITLE
Possible issues getting secret values into tox tests

### ISSUE THREAD

**Issue by thclark** [octue/octue-sdk-python#82]
### What is the expected behavior?

Using:
```
env:
    GCP_SERVICE_ACCOUNT: {{ secrets.GCP_SERVICE_ACCOUNT }}
```
in the tox testing action should lead to the value of that being in the environment ready for testing.

### What is the current behavior?

It doesn't

### Hints

Over in windquest we were able to create a .env file containing secrets - using the following action step:
```
      - name: Create .env File (enables injection of operational secrets into test container)
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_GITHUB_ACTIONS: True
          envkey_CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          envkey_DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          envkey_DJANGO_SECURE_SSL_REDIRECT: True
          envkey_GOOGLE_APPLICATION_ASSETS_BUCKET_NAME: windquest-assets-test-github-actions
          envkey_GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
          envkey_GOOGLE_MAP_API_KEY: ${{ secrets.GOOGLE_MAP_API_KEY }}
          envkey_KOMBU_FERNET_KEY: ${{ secrets.KOMBU_FERNET_KEY }}
          envkey_MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          envkey_MAILGUN_SENDER_DOMAIN: mailgun.wind-pioneers.com
          file_name: .env
```

### Other information

Please give as much detail as you can, like:

- [ ] detailed explanation
- [ ] stacktraces
- [ ] related issues
- [ ] suggestions how to fix
- [ ] links for us to have context, eg. stackoverflow, gitter, etc
